@startuml
class CallCenterApp
class FacadeForAPI {
  {method} memberOnboard(memberId)
  {method} memberAuthenticate(memberId)
  {method} createCredential(...)

}
CallCenterApp -> FacadeForAPI

package "Internal" <<rectangle>> {

note "More complex subsystem" as n1

FacadeForAPI -- "memberHandler"
FacadeForAPI -- "credentialHandler"

class memberHandler {

}

class "credentialHandler" {

}

package "class 2" <<rectangle>> {
}

package "class 3" <<rectangle>> {
}

package "class 4" <<rectangle>> {
}

package "class 5" <<rectangle>> {
}

package "class 6" <<rectangle>> {
}

"memberHandler" -- "class 2"
"memberHandler" -- "class 3"
"class 2" -- "class 4"
"class 3" -- "class 5"
"class 3" -- "class 6"
"class 4" -- "class 5"
"class 4" -- "class 6"
}

note left of CallCenterApp
Happy client whose
           job just became
           easier because of
           the facade.
end note

note right of FacadeForAPI
Unified interface
that is easier to use.
end note
@enduml